"""
API
    block()
        返回：QTextBlock
        获取光标所在的文本块
    blockFormat()
        返回：QTextBlockFormat
        获取光标所在文本块格式
    blockCharFormat()
        返回：QTextCharFormat
        获取光标所在文本块字符格式
    blockNumber()
        返回：int
        返回光标所在文本块编号
    charFormat()
        返回：QTextCharFormat
        获取文本字符格式
    currentFrame()
        返回：QTextFrame
        获取当前所在的框架
    currentList()
        返回：QTextList
        获取当前所在文本列表
    currentTable()
        返回：QTextTable
        获取当前表格

注意
    这些都是光标对象的方法
    光标对象之间调用即可

"""