"""
textChanged()
    文本内容发生改变时，发射信号
selectionChanged()
    选中内容发生改变时，发射信号
cursorPositionChanged()
    光标位置发生改变时，发射信号
currentCharFormatChanged(QTextCharFormat)
    当前字符格式发生改变时，发射信号
copyAvailable(bool)
    复制可用时，发射信号
redoAvailable
    重做可用时，发射信号
undoAvailable()
    撤销可用时，发射信号
"""